Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\urls.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /addprofile
Not Found: /addprofile/
Unauthorized: /addprofile
Unauthorized: /addprofile
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\HospitalManagement\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\HospitalManagement\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Unauthorized: /addprofile
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\views.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /addprofile
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\HospitalManagement\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\HospitalManagement\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\HospitalManagement\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\HospitalManagement\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\HospitalManagement\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\authentication.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\authentication.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /addprofile
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\request.py", line 231, in user
    self._authenticate()
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\backend\hospitalmanagement\patient\authentication.py", line 18, in authenticate
    user = User.objects.get(id=payload['user_id'])
                               ~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\authentication.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\authentication.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /addprofile
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\request.py", line 231, in user
    self._authenticate()
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\backend\hospitalmanagement\patient\authentication.py", line 19, in authenticate
    user = User.objects.get(id=payload['user_id'])
                               ~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\authentication.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /addprofile
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column patient_patientprofile.medical_history does not exist
LINE 1: ...te_of_birth", "patient_patientprofile"."address", "patient_p...
                                                             ^
HINT:  Perhaps you meant to reference the column "patient_patientprofile.medical_historry".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\backend\hospitalmanagement\patient\views.py", line 20, in create
    instance = self.get_object()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\backend\hospitalmanagement\patient\views.py", line 15, in get_object
    return PatientProfile.objects.get(user=self.request.user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\Desktop\Hospital-Management-Main\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column patient_patientprofile.medical_history does not exist
LINE 1: ...te_of_birth", "patient_patientprofile"."address", "patient_p...
                                                             ^
HINT:  Perhaps you meant to reference the column "patient_patientprofile.medical_historry".

C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\patient\authentication.py changed, reloading.
Watching for file changes with StatReloader
Forbidden: /addprofile
Forbidden: /logout
Forbidden: /login
Forbidden: /login
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\user\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\user\views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden: /login
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\user\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Forbidden: /login
C:\Users\user\Desktop\Hospital-Management-Main\Backend\HospitalManagement\HospitalManagement\settings.py changed, reloading.
